controller_list:
  - name: fake_manipulator_controller
    joints:
      - shoulder_1_joint
      - shoulder_2_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint